---
- name: Dixet
  hosts: dixet
  user: fellah
  tasks:
    - file:
        path: $HOME/.cache/web/abs
        state: directory

    - copy:
        src: files/web.conf
        dest: $HOME/.config

    - copy:
        src: files/systemd/web.service
        dest: $HOME/.config/systemd/user

    - systemd:
        user: yes
        enabled: yes
        state: started
        name: web
