#!/bin/bash

alias ls='ls --color=auto'
#alias dmesg='dmesg --color=always'
#alias grep='grep --color=always'
#alias fgrep='fgrep --color=always'
#alias egrep='egrep --color=always'
#alias gcc='gcc -fdiagnostics-color=always'
alias pacman='pacman --color=always'

alias ideaic='ideaic >/dev/null 2>&1 &'
alias phpstorm='phpstorm >/dev/null 2>&1 &'

if [ $HOSTNAME == "zenbook" ]; then
    alias vmstart="VBoxManage startvm --type headless"
fi
