---
- name: Zenbook
  hosts: zenbook
  user: fellah
  become: yes
  become_method: sudo
  tasks:
    - include: tasks/vbox-guest.yml
      when: "'vm' in inventory_hostname"

    - include: tasks/ssh.yml

    - name: Install 'xdg-user-dirs'
      pacman:
        name: xdg-user-dirs
        state: present

    - include: tasks/netctl.yml

    - include: tasks/mtp.yml

    - include: tasks/fellah.yml

    - include: tasks/xorg.yml
