---
- name: Zenbook
  hosts: zenbook
  user: fellah
  become: yes
  become_method: sudo
  tasks:
    - include: tasks/ssh.yml

    # - include: tasks/netctl.yml

    # - include: tasks/mtp.yml

    - include: tasks/fellah.yml

    # - include: tasks/xorg.yml
